### ISSUE TITLE
How to fill in ENV parameters?

### ISSUE THREAD

**Issue by meikoul** [Hitodena/SignalCryptoNewsBot#1]
How to fill in ENV parameters?

**Comment by Hitodena** [comment]
Hi, you need to create a .env file in config. And then fill it with your keys and the pairs that were used in the bot.
URL: its a json response from binance announcements (https://www.binance.com/bapi/composite/v1/public/cms/article/list/query?type=1&pageSize=20&pageNo=1)
WORD: its a word that were figured in binance news (Adds, Launchpool)
PATTERN: its a pattern (re) that you use in string from binance title, to get token
TOKEN: token for your bot in tg
MINUTE: the minute you want to receive notifications from the bot
HOUR: the hour you want to receive notifications from the bot (minute: 20, hour: 13) = (13:20)

**Comment by meikoul** [comment]
> 你好，你需要在配置中创建一个 .env 文件。然后用你的密钥和机器人中使用的对填充它。 URL：它是来自 binance 公告的 json 响应（https://www.binance.com/bapi/composite/v1/public/cms/article/list/query?type=1&pageSize=20&pageNo=1） WORD：它是 binance 新闻（Adds、Launchpool）中计算出的单词 PATTERN：它是你在 binance 标题字符串中使用的模式（re），用于获取令牌 TOKEN：tg 中机器人的令牌 MINUTE：你想要从机器人接收通知的分钟 HOUR：你想要从机器人接收通知的小时（分钟：20，小时：13）=（13:20）

Thanks bro, Is there any delay in the data from this API, for example the official statement was posted at 2:59am EST. However, the post did not show up in the API results until 3:00:14am EST. The interval time ranges from 15 seconds to 74 seconds.

**Comment by Hitodena** [comment]
maybe it has to do with the time zone or the delay of requests, because for me it's about 20 seconds.
